name: Deployment to Google Cloud.

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the GitHub repository from this application.
        uses: actions/checkout@v2

      - name: Build the Docker image for this application and push it into Google Container Registry.
        uses: docker/build-push-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_JSON }}
          dockerfile: ./Dockerfile
          registry: eu.gcr.io
          repository: ${{ secrets.GCP_PROJECT_ID }}/praetorians-arena-api
          tags: latest
          build_args: NEXT_PUBLIC_API_DOMAIN=${{ secrets.NEXT_PUBLIC_API_DOMAIN }}, NEXT_PUBLIC_GA_TRACKING_ID=${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
          push: true

      - name: Setup Google Cloud SDK.
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: latest
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_BASE64 }}
          export_default_credentials: true

      - name: Run the Docker image of this application from Google Container Registry into a Google Cloud Run service.
        run: |
          gcloud --quiet run deploy praetorians-arena-api \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --image eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/praetorians-arena-api \
            --port 3004 \
            --set-env-vars "NODE_ENV=${{ secrets.NODE_ENV }}" \
            --set-env-vars "DB_URI=${{ secrets.DB_URI }}" \
            --set-env-vars "UI_DOMAIN_PROD=${{ secrets.UI_DOMAIN_PROD }}" \
            --set-env-vars "UI_DOMAIN_DEV1=${{ secrets.UI_DOMAIN_DEV1 }}" \
            --set-env-vars "UI_DOMAIN_DEV2=${{ secrets.UI_DOMAIN_DEV2 }}" \
            --set-env-vars "UI_DOMAIN_DEV3=${{ secrets.UI_DOMAIN_DEV3 }}" \
            --set-env-vars "API_DOMAIN=${{ secrets.API_DOMAIN }}" \
            --set-env-vars "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}" \
            --set-env-vars "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
            --set-env-vars "OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" \
            --set-env-vars "OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" \
            --set-env-vars "OAUTH_ACCESS_TOKEN=${{ secrets.sOAUTH_ACCESS_TOKEN }}" \

      - name: Map the running Google Cloud Run service to a custom domain.
        run: |
          gcloud --quiet beta run domain-mappings create \
          --service praetorians-arena-api \
          --domain api.praetorians-arena.nestorllamas.com \
          --platform managed \
          --region europe-west1

      - name: Delete the Docker image of this application from Google Container Registry.
        run: |
          gcloud --quiet container images delete eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/praetorians-arena-api:latest \
          --force-delete-tags
